eBidWEBSITE/Controllers/productController.cs
using eBidWEBSITE.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace eBidWEBSITE.Controllers
{
    public class productController : Controller
    {
        ebidEntities db = new ebidEntities();
        // GET: product


        public ActionResult index()

        {
            return View();
        }
    }
}



//        public ActionResult displayproduct( )
//        {
//            int rt = Convert.ToInt32(Session["Roletype"]);



//                if (rt == 1)
//                {

//                    var query = db.tblProducts.ToList();
//                    return View(query);
//                }
//                else
//                {
//                    int id = Convert.ToInt32(Session["uid"]);
//                    var query = db.tblProducts.Where(x => x.uid == id).ToList();
//                    return View(query);
//                }
//            }










//        public ActionResult addproduct()
//        {
//            List<tblCategory> list = db.tblCategories.ToList();
//            ViewBag.CatList = new SelectList(list, "CatId", "CategoryName");
//            return View();
//        }



//        [HttpPost]
//        public ActionResult addproduct(tblProduct p, HttpPostedFileBase Image)
//        {

//            int id = Convert.ToInt32(Session["uid"]);

//            List<tblCategory> list = db.tblCategories.ToList();
//            ViewBag.CatList = new SelectList(list, "CatId", "CategoryName");


//            if (ModelState.IsValid)
//            {


//                tblProduct pro = new tblProduct();
//                pro.pro_Name = p.pro_Name;
//                pro.pro_Description = p.pro_Description;
//                pro.pro_price = p.pro_price;
//                pro.pro_Image = Image.FileName.ToString();
//                pro.CatId = p.CatId;
//                pro.uid = id;


//                var folder = Server.MapPath("~/productUploads/");
//                Image.SaveAs(Path.Combine(folder, Image.FileName.ToString()));

//                db.tblProducts.Add(pro);
//                db.SaveChanges();

//                return RedirectToAction("displayproduct");
//            }
//            else
//            {
//                TempData["msg"] = "Product Not Upload";
//            }
//            return View();
//        }





//        public ActionResult Edit(int id)
//        {

//            List<tblCategory> list = db.tblCategories.ToList();
//            ViewBag.CatList = new SelectList(list, "CatId", "Name");

//            var query = db.tblProducts.SingleOrDefault(m => m.ProID == id);

//            return View(query);
//        }


//        [HttpPost]
//        public ActionResult Edit(tblProduct p, HttpPostedFileBase Image)
//        {
//            List<tblCategory> list = db.tblCategories.ToList();
//            ViewBag.CatList = new SelectList(list, "CatId", "Name");

//            try
//            {

//                p.pro_Image = Image.FileName.ToString();
//                var folder = Server.MapPath("~/Uploads/");
//                Image.SaveAs(Path.Combine(folder, Image.FileName.ToString()));
//                db.Entry(p).State = EntityState.Modified;
//                db.SaveChanges();

//            }
//            catch (Exception ex)
//            {
//                TempData["msg"] = ex;
//            }

//            return RedirectToAction("displayproduct");

//        }


//        public ActionResult Delete(int id)
//        {
//            var query = db.tblProducts.SingleOrDefault(m => m.ProID == id);
//            db.tblProducts.Remove(query);

//            db.SaveChanges();


//            return RedirectToAction("displayproduct");

//        }



//    }
//}

eBidWEBSITE/Views/product/addproduct.cshtml
@model eBidWEBSITE.Models.tblProduct
@{
    ViewBag.Title = "addproduct";
    Layout = "~/Views/dashboard/_dashboard.cshtml";
}

<h2>addproduct</h2>


@using (Html.BeginForm("addproduct", "product", FormMethod.Post, new { enctype = "multipart/form-data" }))
{

    <div class="container">
        <h2>Add Product</h2>
        <div class="row">
            <div class="col-lg-4">


                <form class="bg-white p-5 contact-form">
                    <div class="form-group">
                        <span>Name:</span>
                        @Html.TextBoxFor(m => m.pro_Name, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <span>Categories:</span>
                        @Html.DropDownListFor(m => m.CatId, ViewBag.CatList as SelectList, "-- Select Category ---")
                    </div>

                    <div class="form-group">
                        <span>Description:</span>
                        @Html.TextBoxFor(m => m.pro_Description, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <span>Unit Price:</span>
                        @Html.TextBoxFor(m => m.pro_price, new { @class = "form-control" })
                    </div>

                    <div class="form-group">
                        <span>Select Image:</span>
                        <input type="file" name="Image" />
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Add Product" class="btn btn-primary py-3 px-5">
                    </div>
                </form>
                <h3 style="color:red;">@TempData["msg"]</h3>

            </div>

        </div>

    </div>
}

eBidWEBSITE/Views/product/displayproduct.cshtml
@model IEnumerable<eBidWEBSITE.Models.tblProduct>
@{
    ViewBag.Title = "displayproduct";
    Layout = "~/Views/dashboard/_dashboard.cshtml";
}

<h2>displayproduct</h2>


<div class="container">
    <h2>View Products</h2>
    <div class="form-group">
        <input type="text" class="form-control col-lg-4 ml-auto" placeholder="Search Here" id="searchBox" />
    </div>
    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Category</th>
                <th>Desc</th>
                <th>Unit</th>
                <th>Image</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody id="myTable">
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.ProID</td>
                    <td>@item.pro_Name</td>
                    <td>@item.tblCategory.CategoryName</td>
                    <td>@item.pro_Description</td>
                    <td>@item.pro_price</td>
                    <td><img src="~/Uploads/@item.pro_Image" style="width:150px; height:100px;" /></td>
                    <td>
                        <a href="@Url.Action("Edit", "Products", new { id = item.ProID})" class="btn btn-primary">Edit</a>
                        <a href="@Url.Action("Delete", "Products", new { id = item.ProID })" class="btn btn-danger">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>


</div>




















<script src="~/js/jquery.min.js"></script>

<script>
    $(document).ready(function () {
        $("#searchBox").on("keyup", function () {
            var value = $(this).val().toLowerCase();
            $("#myTable tr").filter(function () {
                $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
            });
        });
    });
</script>