eBidWEBSITE/Controllers/categoryController.cs
using eBidWEBSITE.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace eBidWEBSITE.Controllers
{
    public class categoryController : Controller
    {
        ebidEntities db = new ebidEntities();
        // GET: category



        public ActionResult displayCategory()
        {
            var query = db.tblCategories.ToList();

            return View(query);
        }




       

        public ActionResult CreateCategory()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateCategory(tblCategory c)
        {
            if (ModelState.IsValid)
            {

                tblCategory cat = new tblCategory();
                cat.CategoryName = c.CategoryName;
                db.tblCategories.Add(cat);
                db.SaveChanges();
                return RedirectToAction("displayCategory");

            }
            else
            {

                TempData["msg"] = "Not Inserted Category";

            }

            return View();
        }











        public ActionResult Edit(int id)
        {

            var query = db.tblCategories.SingleOrDefault(m => m.CatId == id);
            return View(query);
        }

        [HttpPost]
        public ActionResult Edit(tblCategory c)

        {
            try
            {

                db.Entry(c).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("displayCategory");
            }

            catch (Exception ex)

            {
                TempData["msg"] = ex;
            }

            return RedirectToAction("displayCategory");
        }

        

        public ActionResult Delete(int id)

        {

            var query = db.tblCategories.SingleOrDefault(m => m.CatId == id);
            db.tblCategories.Remove(query);
            db.SaveChanges();
            return RedirectToAction("displayCategory");

        }



  

    }
}

eBidWEBSITE/Views/category/CreateCategory.cshtml
@model eBidWEBSITE.Models.tblCategory
@{
    ViewBag.Title = "CreateCategory";
    Layout = "~/Views/dashboard/_dashboard.cshtml";
}

@using (Html.BeginForm())
{

    <div class="container">
        <h2>Add Category</h2>
        <div class="row">
            <div class="col-lg-4">
               

                <form class="bg-white p-5 contact-form">
                    <div class="form-group">
                        <span>Name:</span>
                        @Html.TextBoxFor(m => m.CategoryName, new { @class = "form-control" })
                    </div>

                    <div class="form-group">
                        <input type="submit" value="Add Category" class="btn btn-primary py-3 px-5">
                    </div>
                </form>
                <h3 style="color:red;">@TempData["msg"]</h3>

            </div>

        </div>

    </div>
}

eBidWEBSITE/Views/category/Delete.cshtml
@model eBidWEBSITE.Models.tblCategory

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/dashboard/_dashboard.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>tblCategory</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CategoryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CategoryName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

eBidWEBSITE/Views/category/Edit.cshtml
@model eBidWEBSITE.Models.tblCategory

@using (Html.BeginForm())
{

    <div class="form-horizontal">
        <h4>Update Categories</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CatId)

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CategoryName, new { htmlAttributes = new { @class = "form-control" } })

            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Update" class="btn btn-success" />
            </div>
        </div>
    </div>

    <p>@TempData["msg"]</p>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

eBidWEBSITE/Views/category/displayCategory.cshtml
@model IEnumerable<eBidWEBSITE.Models.tblCategory>
@{
    ViewBag.Title = "displayCategory";
    Layout = "~/Views/dashboard/_dashboard.cshtml";
}

<h2>displayCategory</h2>






<div class="container">
    <h2>View Category</h2>
    <div class="form-group">
        <input type="text" class="form-control col-lg-4 ml-auto" placeholder="Search Here" id="searchBox" />
    </div>
    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody id="myTable">
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.CatId</td>
                    <td>@item.CategoryName</td>
                    <td>
                        <a href="@Url.Action("Edit", "Category", new { id = item.CatId})" class="btn btn-info">Edit</a>
                        <a href="@Url.Action("Delete", "Category", new { id = item.CatId})" class="btn btn-danger">Delete</a>
                    </td>

                </tr>
            }
        </tbody>
    </table>

    @Html.ActionLink("return", "CreateCategory", "category")
</div>


<script src="~/js/jquery.min.js"></script>

<script>
    $(document).ready(function () {
        $("#searchBox").on("keyup", function () {
            var value = $(this).val().toLowerCase();
            $("#myTable tr").filter(function () {
                $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
            });
        });
    });
</script>