eBidWEBSITE/Controllers/BIDController.cs
using eBidWEBSITE.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace eBidWEBSITE.Controllers
{
    public class BIDController : Controller
    {
        ebidEntities db = new ebidEntities();

        List<Cart> li = new List<Cart>();






        // GET: BID


















        public ActionResult displaybid()
        {
            int rt = Convert.ToInt32(Session["Roletype"]);

            if (rt == 1)
            {

                var query = db.tblBids.ToList();
                return View(query);
            }
            else
            {
                int id = Convert.ToInt32(Session["uid"]);
                var query = db.tblBids.Where(x => x.uid == id).ToList();
                return View(query);
            }

        }








        public ActionResult addbid()
        {
            List<tblbidcategory> list = db.tblbidcategories.ToList();
            ViewBag.CatList = new SelectList(list, "BidcatId", "Bidcatname");
            return View();
        }



        [HttpPost]
        public ActionResult addbid(tblBid b, HttpPostedFileBase Image)
        {
            List<tblbidcategory> list = db.tblbidcategories.ToList();
            ViewBag.Catlist = new SelectList(list, "BidcatId", "Bidcatname");

            int id = Convert.ToInt32(Session["uid"]);
            if (ModelState.IsValid)
            {


                tblBid bidding = new tblBid();
                bidding.bid_Name = b.bid_Name;
                bidding.bid_Description = b.bid_Description;
                bidding.bid_MINamount = b.bid_MINamount;
                bidding.bid_Image = Image.FileName.ToString();



                




                bidding.bid_endTime = b.bid_endTime;




                bidding.CatId = b.CatId;   
                bidding.uid = id;


                var folder = Server.MapPath("~/bidsUploads/");
                Image.SaveAs(Path.Combine(folder, Image.FileName.ToString()));

                db.tblBids.Add(bidding);
                db.SaveChanges();

                return RedirectToAction("displaybid");
            }
            else
            {
                TempData["msg"] = "Product Not Upload";
            }
            return View();
        }







        


           public ActionResult Delete(int id)
           {
               var query = db.tblBids.SingleOrDefault(m => m.BidID == id);
               db.tblBids.Remove(query);

               db.SaveChanges();


               return RedirectToAction("displayproduct");

           }

















        public ActionResult AddtoCart(int id)
        {
            var query = db.tblBids.Where(x => x.BidID == id).SingleOrDefault();
            return View(query);

        }

        [HttpPost]
        public ActionResult AddtoCart(int id, int bidding)
        {

            tblBid p = db.tblBids.Where(x => x.BidID == id).SingleOrDefault();
            Cart c = new Cart();
            c.BidID = id;
            c.bid_Name = p.bid_Name;
            c.bid_MINamount = Convert.ToInt32(p.bid_MINamount);
            c.bidding = Convert.ToInt32(bidding);
            c.bill = c.bidding;

            if (TempData["cart"] == null)
            {

                li.Add(c);
                TempData["cart"] = li;

            }

            else
            {

                List<Cart> li2 = TempData["cart"] as List<Cart>;
                int flag = 0;
                foreach (var item in li2)
                {
                    if (item.BidID == c.BidID)
                    {
                        item.bidding += c.bidding;
                        item.bill += c.bill;
                        flag = 1;
                    }
                }

                if (flag == 0)

                {
                    li2.Add(c);

                }

                TempData["cart"] = li2;
            }

            TempData.Keep();
            return RedirectToAction("Index");
        }



        public ActionResult removecart(int? id)
        {

            if (TempData["cart"] == null)

            {
                TempData.Remove("total");

                TempData.Remove("cart");
            }

            else

            {
                List<Cart> li2 = TempData["cart"] as List<Cart>;

                Cart c = li2.Where(x => x.BidID == id).SingleOrDefault();

                li2.Remove(c);
                int s = 0;

                foreach (var item in li2)

                {

                    s += item.bill;
                }

                TempData["total"] = s;

            }

            return View();
        }



        






       public ActionResult Checkout()
       {
           TempData.Keep();
           return View();
       }

       [HttpPost]
       public ActionResult Checkout(string contact, string address)
       {

           if (ModelState.IsValid)

           {
               List<Cart> li2 = TempData["cart"] as List<Cart>;
               tblInvoice iv = new tblInvoice();
               iv.UserId = Convert.ToInt32(Session["uid"].ToString());
               iv.InvoiceDate = System.DateTime.Now;
               iv.Bill = (int)TempData["total"];
               iv.Payment = "cash";
               db.tblInvoices.Add(iv);
               db.SaveChanges();



               foreach (var item in li2)

               {

                   tblOrder od = new tblOrder();
                   od.bidid = item.BidID;
                   od.Contact = contact;
                   od.Address = address;
                   od.OrderDate = System.DateTime.Now;
                   od.InvoiceId = iv.InvoiceId;
                
                   od.Unit = item.bid_MINamount;
                   od.bidding = item.bidding;
                   od.Total = item.bill;
                   db.tblOrders.Add(od);
                   db.SaveChanges();

               }

               TempData.Remove("total");
               TempData.Remove("cart");
               TempData["msg"] = "Order Book Successfully!!";
               return RedirectToAction("Index");
           }

           TempData.Keep();
           return View();
       }

































    }
}

eBidWEBSITE/Views/bid/AddtoCart.cshtml
@model eBidWEBSITE.Models.tblBid
@{
    ViewBag.Title = "AddtoCart";
    Layout = "~/Views/Shared/_Layout.cshtml";
}











@using (Html.BeginForm())
{

    <div class="card-wrapper">
        <div class="card" style="min-width:900px; min-height:600px;">
            <!-- card left -->
            <div class="product-imgs">
                <div class="img-display">
                    <div class="img-showcase">
                        <img src="~/bidsUploads/@Model.bid_Image" style="height:250px;width:50%" />

                    </div>
                </div>

            </div>
            <!-- card right -->
            <div class="product-content">
                <h2 class="product-title">@Model.bid_Name</h2>


                <div class="product-price">

                    <p class="new-price">Price per Unit: <span>$@Model.bid_MINamount </span></p>
                </div>
                <div class="product-detail">
                    <h2>Detail: </h2>
                    <p>@Model.bid_Description</p>
                   

                </div>


                <div class="cown-down1">

                    <div class="content">

                        <div class="coming-time">

                            <div class="clearfix" data-countdown="2022/02/30"></div>
                        </div>
                    </div>
                </div>

            

                       
                           
                        
                 


                        <div class="purchase-info">
                            <input type="number" min="@Model.bid_MINamount" value="@Model.bid_MINamount" max="" name="bidding" class="quantity-input" data-quantity-target="" />




                            <button type="submit" value="Add to Cart" class="btn" style="min-width:60px;">

                                Add to Cart <i class="fa-solid fa-gavel"></i>
                            </button>

                        </div>

                    </div>
                </div>
            </div>


}


<style>
    .cown-down1 {
        position: relative;
        height: 100px;
        overflow: hidden;
    }

       

        .cown-down1 .padding-left {
            padding-left: 0;
        }

       

        .cown-down1 .content {
            text-align: center;
            background: #FDFBEF;
            height: 100%;
            position: relative;
        }

            .cown-down1 .content .heading-block {
                position: absolute;
                left: 0;
                top: 50%;
                transform: translateY(-50%);
                padding: 75px;
            }

            .cown-down1 .content .small-title {
                font-size: 13px;
                color: #777;
                display: block;
                text-transform: uppercase;
                margin-bottom: 5px;
                font-weight: 600;
            }

            .cown-down1 .content .title {
                font-size: 25px;
                font-weight: 600;
                margin-bottom: 20px;
                text-transform: capitalize;
            }

            .cown-down1 .content .price {
                margin-top: 35px;
                font-size: 35px;
                font-weight: 700;
                color: #be263f;
            }

                .cown-down1 .content .price s {
                    margin-top: 35px;
                    font-size: 24px;
                    font-weight: 500;
                    color: #666;
                }

            .cown-down1 .content .cdown {
                float: left;
                text-align: center;
                margin-top: 40px;
                width: 80px;
                display: inline-block;
            }

          
            .cown-down1 .content .cdown {
                display: inline-block;
            }

                .cown-down1 .content .cdown span {
                    color: #333;
                    font-size: 22px;
                    font-weight: 400;
                    text-transform: uppercase;
                }

                .cown-down1 .content .cdown p {
                    font-size: 13px;
                    color: #666;
                    text-transform: uppercase;
                }
</style>





            
            
        
   






















<link rel="stylesheet" href="~/css/font-awesome.css">
<link href="~/css/detailpage.css" rel="stylesheet" />

eBidWEBSITE/Views/bid/Checkout.cshtml
@model eBidWEBSITE.Models.tblBid
@{
    ViewBag.Title = "Checkout";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Checkout</h2>



<!-- Breadcrumbs -->
<div class="breadcrumbs">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="bread-inner">
                    <ul class="bread-list">
                        <li><a href="index1.html">Home<i class="ti-arrow-right"></i></a></li>
                        <li class="active"><a href="blog-single.html">Cart</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End Breadcrumbs -->
<!-- Shopping Cart -->
<div class="shopping-cart section">
    <div class="container">

        <div class="row">
            @if (TempData["total"] == null)
            {
                <h1>cart is empty</h1>

            }
            else
            {
                <div class="col-12">
                    <!-- Shopping Summery -->
                    <table class="table shopping-summery">
                        <thead>
                            <tr class="main-hading">
                                <th>ID</th>
                                <th>PRODUCT</th>
                                <th>NAME</th>
                                <th class="text-center">UNIT PRICE</th>
                                <th class="text-center">QUANTITY</th>
                                <th class="text-center">TOTAL</th>
                                <th class="text-center"><i class="ti-trash remove-icon"></i></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in TempData["cart"] as List<eBidWEBSITE.Models.Cart>)
                            {

                                <tr>

                                    <td class="product-name">
                                        <h5>@item.BidID</h5>
                                    </td>

                                    <td class="image" data-title="No"><img src="https://via.placeholder.com/100x100" alt="#"></td>
                                    <td class="product-des" data-title="Description">
                                        <p class="product-name"><a href="#">@item.bid_Name</a></p>

                                    </td>
                                    <td class="price" data-title="MIN Amount"><span>@item.bid_MINamount </span></td>
                                    <td class="bidding" data-title="bidding">
                                        <!-- Input Order -->
                                        @item.bidding
                                        <!--/ End Input Order -->
                                    </td>
                                    <td class="total-amount" data-title="Total"><span>@item.bill</span></td>
                                    <td class="action" data-title="Remove"><a href="@Url.Action("removecart", "Home", new { id = item.BidID })"><i class="ti-trash remove-icon"></i></a></td>



                                </tr>
                            }
                        </tbody>
                    </table>
                    <!--/ End Shopping Summery -->
                </div>
            }
        </div>









        @if (!User.Identity.IsAuthenticated)
            {
            <div class="row">
                <div class="col-12">
                    <div class="total-amount">
                        <div class="row">
                            <div class="col-lg-8 col-md-5 col-12">
                                <div class="left">

                                    <a href="@Url.Action("Login","Account")" class="btn btn-primary py-3 px-4">Login</a>
                                    <a href="@Url.Action("Register","Account")" class="btn btn-primary py-3 px-4">Register</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }


        <div class="row">
            <div class="col-12">
                <div class="total-amount">
                    <div class="row">
                        <div class="col-lg-4 col-md-7 col-12 ">
                            <div class="right">
                                <ul>

                                    <li>Shipping<span>Free</span></li>

                                    <li class="last">You Pay<span>Rs.@TempData["total"]</span></li>
                                </ul>

                                @if (User.Identity.IsAuthenticated)
                                {
                                    if (User.IsInRole("2"))
                                    {

                                        if (TempData["cart"] != null)
                                        {
                                            using (Html.BeginForm())
                                            {

                                                <div class="button5 text-right">
                                                    <span>Contact :</span> <input type="text" name="contact" class="form-control col-lg-6" />
                                                    <span>Address :</span><textarea name="address" class="form-control col-lg-6"></textarea>
                                                    <a class="btn btn-dark" value=>
                                                        <input type="submit" />
                                                    </a>


                                                </div>

                                            }
                                        }
                                    }
                                }
                            </div>


                        </div>

                    </div>
                </div>

                <!--/ End Total Amount -->
            </div>
        </div>
    </div>
</div>
<!--/ End Shopping Cart -->
<!-- Start Shop Services Area  -->
<section class="shop-services section">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-6 col-12">
                <!-- Start Single Service -->
                <div class="single-service">
                    <i class="ti-rocket"></i>
                    <h4>Free shiping</h4>
                    <p>Orders over $100</p>
                </div>
                <!-- End Single Service -->
            </div>
            <div class="col-lg-3 col-md-6 col-12">
                <!-- Start Single Service -->
                <div class="single-service">
                    <i class="ti-reload"></i>
                    <h4>Free Return</h4>
                    <p>Within 30 days returns</p>
                </div>
                <!-- End Single Service -->
            </div>
            <div class="col-lg-3 col-md-6 col-12">
                <!-- Start Single Service -->
                <div class="single-service">
                    <i class="ti-lock"></i>
                    <h4>Sucure Payment</h4>
                    <p>100% secure payment</p>
                </div>
                <!-- End Single Service -->
            </div>
            <div class="col-lg-3 col-md-6 col-12">
                <!-- Start Single Service -->
                <div class="single-service">
                    <i class="ti-tag"></i>
                    <h4>Best Peice</h4>
                    <p>Guaranteed price</p>
                </div>
                <!-- End Single Service -->
            </div>
        </div>
    </div>
</section>
<!-- End Shop Newsletter -->
<!-- Start Shop Newsletter  -->
<section class="shop-newsletter section">
    <div class="container">
        <div class="inner-top">
            <div class="row">
                <div class="col-lg-8 offset-lg-2 col-12">

                </div>
            </div>
        </div>
    </div>
</section>
<!-- End Shop Newsletter -->
    <

eBidWEBSITE/Views/bid/addbid.cshtml
@model eBidWEBSITE.Models.tblBid
@{
    ViewBag.Title = "displaybid";
    Layout = "~/Views/dashboard/_dashboard.cshtml";
}
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/calendercustom.js"></script>
<script src="~/Scripts/bootstrap-datetimepicker.min.js"></script>
<script src="~/Scripts/moment.min.js"></script>
<link href="~/Content/bootstrap-datetimepicker.min.css" rel="stylesheet" />
<script src="~/js/jquery.min.js"></script>
<script src="~/js/jquery-migrate-3.0.0.js"></script>
<script src="~/js/jquery-ui.min.js"></script>
<link href="~/Content/bootstrap-datetimepicker.min.css" rel="stylesheet" />
<link href="~/Content/themes/base/datepicker.css" rel="stylesheet" />
<script src="~/Content/dashboard/jquery.js"></script>
<script src="~/Content/dashboard/jquery-3.3.1.min.js"></script>

 <script>
     $(function () {
         $(".datepicker").datepicker();
     });
 </script>

<link rel="stylesheet" href="~//code.jquery.com/ui/1.13.1/themes/base/jquery-ui.css">
<link rel="stylesheet" href="~/resources/demos/style.css">
<script src="https://code.jquery.com/jquery-3.6.0.js"></script>
<script src="https://code.jquery.com/ui/1.13.1/jquery-ui.js"></script>



@using (Html.BeginForm("addbid", "BID", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
<div class="container">
    <div class="title text-center">ADD YOUR BID</div>
    <div class="content text-center">
        
            <div class="user-details text-center">
                <div class="input-box text-center ">
                    <span class="details">Product Name</span>
                    @Html.TextBoxFor(m => m.bid_Name, new { @class = "form-control" })
                </div>
                <div class="input-box text-center">
                    <span class="details">Category</span>
                    @Html.DropDownListFor(m => m.CatId, ViewBag.CatList as SelectList, "-- Select Category ---")
                </div>
                <div class="input-box text-center">
                    <span class="details">Starting bid </span>
                    @Html.TextBoxFor(m => m.bid_MINamount, new { @class = "form-control" })
                </div>

                <div class="input-box text-center">
                    <span class="details">End Date:</span>
                    @Html.EditorFor(m => m.bid_endTime, new { htmlAttributes = new { @class = "datepicker" } })

                </div>


                <div class="form-group input-box message text-center">
                    <label>Product Description<span>*</span></label>

                    @Html.TextBoxFor(m => m.bid_Description, new { @class = "form-control" })

                </div>
            </div>


          
                        <span>Select Image:</span>
                        <input type="file" name="Image" />
                   <br>
        <br>
        <div class="form-group">
            <input type="submit" value="Register" class="btn btn-primary py-3 px-5">
        </div>
         
          
               
            
        <h3 style="color:red;">@TempData["msg"]</h3>
        </div>
    </div>
 

    }

























<link href="~/css/form.css" rel="stylesheet" />

eBidWEBSITE/Views/bid/displaybid.cshtml
@model IEnumerable<eBidWEBSITE.Models.tblBid>

@{
    ViewBag.Title = "displaybid";
    Layout = "~/Views/dashboard/_dashboard.cshtml";
}


<link rel="stylesheet" href="~/css/reset.css">

<link rel="stylesheet" href="~/css/responsive.css">

<link rel="stylesheet" href="~/css/font-awesome.css">










<!-- End Breadcrumbs -->
@*<!-- Shopping Cart -->
<div class="shopping-cart section">
  

        <div class="row">





            <div class="col-12">
                <!-- Shopping Summery -->
                <table class="table shopping-summery">
                    <thead>
                        <tr class="main-hading">

                            <th>Image</th>
                            <th>PRODUCT</th>
                           
                            <th class="text-center">Bid PRICE</th>
                            <th class="text-center">Description</th>
                            <th class="text-center">End Date</th>
                            <th class="text-center"><i class="ti-trash remove-icon"></i>delete</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {

                            <tr>

                                <td class="image" data-title="No"><img src="~/bidsUploads/@item.bid_Image" alt="#"></td>
                                <td class="product-name">

                                    @Html.DisplayFor(modelItem => item.bid_Name)
                                </td>


                              

                                <td class="price" data-title="MIN Amount"><span> @item.bid_MINamount</span></td>



                                <td class="product-des" data-title="Description">
                                    <div class="ui-widget-content resizable">
                                        <p class="ui-widget-header">@item.bid_Description</p>
                                    </div>
                                  

                                </td>

                                <td class="total-amount" ><span>@item.bid_endTime)</span></td>


                                <td class="action" data-title="Remove"><a href="@Url.Action("Delete", "BID", new { id = item.BidID })"><i class="ti-trash remove-icon" style="color:#808080;"></i></a></td>



                            </tr>
                        }
                    </tbody>
                </table>
                <!--/ End Shopping Summery -->
            </div>
        </div>
    </div>*@
      















<div class="container-fluid py-4">
    <div class="row">
        <div class="col-12">
            <div class="card my-4">
                <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
                    <div class="bg-gradient-primary shadow-primary border-radius-lg pt-4 pb-3">
                        <h6 class="text-white text-capitalize ps-3">BIDS PRODUCTS LIST</h6>
                    </div>
                </div>
                <div class="card-body px-0 pb-2">
                    <div class="table-responsive p-0">
                        <table class="table align-items-center mb-0">
                            <thead>
                                <tr>
                                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Bid</th>
                                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">NAME</th>
                                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Category</th>

                                    <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Bid PRICE</th>
                                  
                                    <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">End Date</th>
                                    <th class="text-secondary opacity-7">Delete</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            <div class="d-flex px-2 py-1">
                                                <div>
                                                    <img src="~/bidsUploads/@item.bid_Image" class="avatar avatar-sm me-3 border-radius-lg" alt="user1">
                                                </div>
                                                
                                                    
                                               
                                            </div>
                                        </td>
                                        <td>
                                            <p class="text-xs font-weight-bold mb-0">@item.bid_Name</p>
                                            <p class="text-xs text-secondary mb-0">eBid</p>
                                        </td>
                                        <td>
                                            <p class="text-xs font-weight-bold mb-0">@item.tblbidcategory.Bidcatname</p>
                                            <p class="text-xs text-secondary mb-0">eBid</p>
                                        </td>
                                        <td class="align-middle text-center text-sm">
                                            <span class="badge badge-sm bg-gradient-success">@item.bid_MINamount</span>
                                        </td>
                                      
                                        <td class="align-middle text-center">
                                            <span class="text-secondary text-xs font-weight-bold">@item.bid_endTime</span>
                                        </td>
                                        
                                        <td class="action" data-title="Remove"><a href="@Url.Action("Delete", "BID", new { id = item.BidID })">Delete</a></td>
                                             
                                          
                                    </tr>
                                }

                               


                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>


</div>





































<link href="~/https://fonts.googleapis.com/css?family=Poppins:200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i&display=swap" rel="stylesheet">
<link rel="stylesheet" href="~/https://use.fontawesome.com/releases/v5.15.4/css/all.css" integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous" />
<link rel="stylesheet" href="~/code.jquery.com/ui/1.13.1/themes/base/jquery-ui.css">
<link rel="stylesheet" href="~/resources/demos/style.css">
<style>
    #resizable {
        width: 150px;
        height: 150px;
        padding: 0.5em;
    }

        #resizable h3 {
            text-align: center;
            margin: 0;
        }
</style>
<script src="https://code.jquery.com/jquery-3.6.0.js"></script>
<script src="https://code.jquery.com/ui/1.13.1/jquery-ui.js"></script>
<script>
  $( function() {
    $( ".resizable" ).resizable();
  } );
</script>


    